### ISSUE TITLE
Unclear documentation / Readme

### ISSUE THREAD

**Issue by ignoramous** [BinaryAnalysisPlatform/holmes#7]
It is unclear what "integrating mutliple analysis using a logic langauge" means.

Can the readme / wiki be a bit more elaborate with how-tos, use-cases and screenshots, if possible.

Thanks.

**Comment by maurer** [comment]
This software is still in early development, and not suitable for general use.

If you really want to see what I'm trying to do, feel free to read my [proposal](http://data.matthewmaurer.org/proposal.pdf) for a description of my goals.

If you're just looking for potentially useful tools, maybe check back in 6 months or so and it may be in a closer-to-alpha state.

**Comment by kalenedrael** [comment]
uma d?

**Comment by ignoramous** [comment]
Is it in Alpha stage now?

**Comment by maurer** [comment]
No. There will be a release or a change in the readme when it is ready for any kind of use.
